spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algafooddb?serverTimezone=UTC&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 1000


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
      #       database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/ddl.sql
    show-sql: true
  #     generate-ddl: true
  #      hibernate:
  #        ddl-auto: none


