spring:
  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  datasource:
    url: jdbc:mysql://localhost:3306/algafooddb?serverTimezone=UTC&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 1000


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
      #       database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    show-sql: true
  #     generate-ddl: true
  #      hibernate:
  #        ddl-auto: none


