version: '3.3'

services:
  mysql-compose:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'algafooddb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

